// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from com_polestar_naosdk_api.djinni

#import <Foundation/Foundation.h>


@protocol PSTICallback

- (void)onSuccess:(nonnull NSString *)msg;

- (void)onFailure:(nonnull NSString *)msg;

@end
